name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Copy README
        run: cp README.md packages/upset/README.md
      - name: Extract tag name
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/} || echo ::set-output name=TAG::latest
      - name: Change directory and publish
        run: cd packages/upset && npm publish --tag ${{ steps.get_tag.outputs.TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
