name: Publish Packages to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core, upset]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Copy README
        run: cp README.md packages/${{ matrix.package }}/README.md
      - name: Extract tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Update core dependency in upset package
        if: matrix.package == 'upset'
        run: |
          cd packages/upset
          npm pkg set dependencies.@visdesignlab/upset2-core="${{ steps.get_tag.outputs.TAG }}"
      - name: Update package version and publish
        run: |
          cd packages/${{ matrix.package }}
          npm version ${{ steps.get_tag.outputs.TAG }} --no-git-tag-version
          npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
